Disable Mac bundle creation in release workflow
Comment out Mac editor and template bundle creation steps.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -94,90 +94,90 @@ jobs:
           SIGNING_IDENTITY=$(security find-identity -v -p codesigning | awk -F'"' 'NR==1 {print $2}')
           echo "APPLE_SIGNING_IDENTITY=$SIGNING_IDENTITY" >> $GITHUB_ENV
   
-      - name: Mac Create Editor Bundle
-        if: ${{ env.BUILD_CERTIFICATE_BASE64 != '' }}
-        run: |
-          cp -r misc/dist/macos_tools.app ./bin/Godot.app
-          mkdir -p bin/Godot.app/Contents/MacOS
-          cp bin/godot.macos.editor.universal bin/Godot.app/Contents/MacOS/Godot
-          chmod +x bin/Godot.app/Contents/MacOS/Godot
-          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements --sign "${{ env.APPLE_SIGNING_IDENTITY }}" bin/Godot.app
+      # - name: Mac Create Editor Bundle
+      #   if: ${{ env.BUILD_CERTIFICATE_BASE64 != '' }}
+      #   run: |
+      #     cp -r misc/dist/macos_tools.app ./bin/Godot.app
+      #     mkdir -p bin/Godot.app/Contents/MacOS
+      #     cp bin/godot.macos.editor.universal bin/Godot.app/Contents/MacOS/Godot
+      #     chmod +x bin/Godot.app/Contents/MacOS/Godot
+      #     codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements --sign "${{ env.APPLE_SIGNING_IDENTITY }}" bin/Godot.app
 
-          # Package the application into a zip file
-          zip -q -9 -r "Godot.universal.zip" bin/Godot.app
+      #     # Package the application into a zip file
+      #     zip -q -9 -r "Godot.universal.zip" bin/Godot.app
 
-          /Applications/Xcode.app/Contents/Developer/usr/bin/notarytool store-credentials "AppleID" --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID }}"
+      #     /Applications/Xcode.app/Contents/Developer/usr/bin/notarytool store-credentials "AppleID" --apple-id "${{ secrets.APPLE_ID }}" --password "${{ secrets.APP_SPECIFIC_PASSWORD }}" --team-id "${{ secrets.APPLE_TEAM_ID }}"
 
-          /Applications/Xcode.app/Contents/Developer/usr/bin/notarytool submit Godot.universal.zip --wait --keychain-profile "AppleID"
+      #     /Applications/Xcode.app/Contents/Developer/usr/bin/notarytool submit Godot.universal.zip --wait --keychain-profile "AppleID"
 
-          xcrun stapler staple bin/Godot.app
+      #     xcrun stapler staple bin/Godot.app
 
-      - name: Mac Create Mono Editor Bundle
-        if: ${{ env.BUILD_CERTIFICATE_BASE64 != '' }}
-        run: |
-          set -e
-          if [ ! -f bin/godot.macos.editor.mono.universal ]; then
-            echo "Mono macOS editor binary not found, skipping."
-            exit 0
-          fi
-          cp -r misc/dist/macos_tools.app ./bin/Godot_mono.app
-          cp -r bin/GodotSharp bin/Godot_mono.app/Contents/Resources
-          mkdir -p bin/Godot_mono.app/Contents/MacOS
-          cp bin/godot.macos.editor.mono.universal bin/Godot_mono.app/Contents/MacOS/Godot
-          chmod +x bin/Godot_mono.app/Contents/MacOS/Godot
-          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements --sign "${{ env.APPLE_SIGNING_IDENTITY }}" bin/Godot_mono.app
+      # - name: Mac Create Mono Editor Bundle
+      #   if: ${{ env.BUILD_CERTIFICATE_BASE64 != '' }}
+      #   run: |
+      #     set -e
+      #     if [ ! -f bin/godot.macos.editor.mono.universal ]; then
+      #       echo "Mono macOS editor binary not found, skipping."
+      #       exit 0
+      #     fi
+      #     cp -r misc/dist/macos_tools.app ./bin/Godot_mono.app
+      #     cp -r bin/GodotSharp bin/Godot_mono.app/Contents/Resources
+      #     mkdir -p bin/Godot_mono.app/Contents/MacOS
+      #     cp bin/godot.macos.editor.mono.universal bin/Godot_mono.app/Contents/MacOS/Godot
+      #     chmod +x bin/Godot_mono.app/Contents/MacOS/Godot
+      #     codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements --sign "${{ env.APPLE_SIGNING_IDENTITY }}" bin/Godot_mono.app
 
-          zip -q -9 -r "Godot_mono.universal.zip" bin/Godot_mono.app
+      #     zip -q -9 -r "Godot_mono.universal.zip" bin/Godot_mono.app
 
-          /Applications/Xcode.app/Contents/Developer/usr/bin/notarytool submit Godot_mono.universal.zip --wait --keychain-profile "AppleID"
+      #     /Applications/Xcode.app/Contents/Developer/usr/bin/notarytool submit Godot_mono.universal.zip --wait --keychain-profile "AppleID"
 
-          xcrun stapler staple bin/Godot_mono.app
+      #     xcrun stapler staple bin/Godot_mono.app
 
-      - name: Mac Create Editor Bundle (w/o Signing)
-        if: ${{ env.BUILD_CERTIFICATE_BASE64 == '' }}
-        run: |
-          cp -r misc/dist/macos_tools.app ./bin/Godot.app
-          mkdir -p bin/Godot.app/Contents/MacOS
-          cp bin/godot.macos.editor.universal bin/Godot.app/Contents/MacOS/Godot
-          chmod +x bin/Godot.app/Contents/MacOS/Godot
-          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - bin/Godot.app
+      # - name: Mac Create Editor Bundle (w/o Signing)
+      #   if: ${{ env.BUILD_CERTIFICATE_BASE64 == '' }}
+      #   run: |
+      #     cp -r misc/dist/macos_tools.app ./bin/Godot.app
+      #     mkdir -p bin/Godot.app/Contents/MacOS
+      #     cp bin/godot.macos.editor.universal bin/Godot.app/Contents/MacOS/Godot
+      #     chmod +x bin/Godot.app/Contents/MacOS/Godot
+      #     codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - bin/Godot.app
 
-      - name: Mac Create Mono Editor Bundle (w/o Signing)
-        if: ${{ env.BUILD_CERTIFICATE_BASE64 == '' }}
-        run: |
-          set -e
-          if [ ! -f bin/godot.macos.editor.mono.universal ]; then
-            echo "Mono macOS editor binary not found, skipping."
-            exit 0
-          fi
-          cp -r misc/dist/macos_tools.app ./bin/Godot_mono.app
-          mkdir -p bin/Godot_mono.app/Contents/MacOS
-          cp bin/godot.macos.editor.mono.universal bin/Godot_mono.app/Contents/MacOS/Godot
-          chmod +x bin/Godot_mono.app/Contents/MacOS/Godot
-          codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - bin/Godot_mono.app
+      # - name: Mac Create Mono Editor Bundle (w/o Signing)
+      #   if: ${{ env.BUILD_CERTIFICATE_BASE64 == '' }}
+      #   run: |
+      #     set -e
+      #     if [ ! -f bin/godot.macos.editor.mono.universal ]; then
+      #       echo "Mono macOS editor binary not found, skipping."
+      #       exit 0
+      #     fi
+      #     cp -r misc/dist/macos_tools.app ./bin/Godot_mono.app
+      #     mkdir -p bin/Godot_mono.app/Contents/MacOS
+      #     cp bin/godot.macos.editor.mono.universal bin/Godot_mono.app/Contents/MacOS/Godot
+      #     chmod +x bin/Godot_mono.app/Contents/MacOS/Godot
+      #     codesign --force --timestamp --options=runtime --entitlements misc/dist/macos/editor.entitlements -s - bin/Godot_mono.app
 
-      - name: Mac Create Template Bundle
-        run: |
-          cp -r misc/dist/macos_template.app ./bin
-          mkdir -p bin/macos_template.app/Contents/MacOS
-          cp bin/godot.macos.template_release.universal bin/macos_template.app/Contents/MacOS/godot_macos_release.universal
-          cp bin/godot.macos.template_debug.universal bin/macos_template.app/Contents/MacOS/godot_macos_debug.universal
-          chmod +x bin/macos_template.app/Contents/MacOS/godot_macos*
-          cd bin && zip -q -9 -r macos.zip macos_template.app && cd ..
+      # - name: Mac Create Template Bundle
+      #   run: |
+      #     cp -r misc/dist/macos_template.app ./bin
+      #     mkdir -p bin/macos_template.app/Contents/MacOS
+      #     cp bin/godot.macos.template_release.universal bin/macos_template.app/Contents/MacOS/godot_macos_release.universal
+      #     cp bin/godot.macos.template_debug.universal bin/macos_template.app/Contents/MacOS/godot_macos_debug.universal
+      #     chmod +x bin/macos_template.app/Contents/MacOS/godot_macos*
+      #     cd bin && zip -q -9 -r macos.zip macos_template.app && cd ..
 
-      - name: Mac Create Template Bundle (Mono)
-        run: |
-          set -e
-          if [ ! -f bin/godot.macos.template_release.mono.universal ] || [ ! -f bin/godot.macos.template_debug.mono.universal ]; then
-            echo "Mono macOS template binaries not found, skipping."
-            exit 0
-          fi
-          cp -r misc/dist/macos_template.app ./bin/macos_template_mono.app
-          mkdir -p bin/macos_template_mono.app/Contents/MacOS
-          cp bin/godot.macos.template_release.mono.universal bin/macos_template_mono.app/Contents/MacOS/godot_macos_release.universal
-          cp bin/godot.macos.template_debug.mono.universal bin/macos_template_mono.app/Contents/MacOS/godot_macos_debug.universal
-          chmod +x bin/macos_template_mono.app/Contents/MacOS/godot_macos*
-          cd bin && zip -q -9 -r macos_mono.zip macos_template_mono.app && cd ..
+      # - name: Mac Create Template Bundle (Mono)
+      #   run: |
+      #     set -e
+      #     if [ ! -f bin/godot.macos.template_release.mono.universal ] || [ ! -f bin/godot.macos.template_debug.mono.universal ]; then
+      #       echo "Mono macOS template binaries not found, skipping."
+      #       exit 0
+      #     fi
+      #     cp -r misc/dist/macos_template.app ./bin/macos_template_mono.app
+      #     mkdir -p bin/macos_template_mono.app/Contents/MacOS
+      #     cp bin/godot.macos.template_release.mono.universal bin/macos_template_mono.app/Contents/MacOS/godot_macos_release.universal
+      #     cp bin/godot.macos.template_debug.mono.universal bin/macos_template_mono.app/Contents/MacOS/godot_macos_debug.universal
+      #     chmod +x bin/macos_template_mono.app/Contents/MacOS/godot_macos*
+      #     cd bin && zip -q -9 -r macos_mono.zip macos_template_mono.app && cd ..
 
       - name: Assemble Android sources (debug + release) into one zip
         run: |
